### ISSUE TITLE
Local dev steps

### ISSUE THREAD

**Issue by bertocq** [ortegacmanuel/consulnetwork#1]
I'm trying to use this locally to contribute, I did:
```
git clone git@github.com:ortegacmanuel/consulnetwork.git
cd consulnetwork
bundle
ruby app.rb
```
But in return I get:
```
app.rb:5:in `<main>': uninitialized constant Sinatra (NameError)
```

After adding `require 'sinatra'` at https://github.com/bertocq/consulnetwork/blob/master/app.rb#L4 I'm still getting:
```
app.rb:9:in `block in <class:ConsulNetwork>': uninitialized constant Sinatra::Reloader (NameError)
	from /Users/bertocq/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1423:in `configure'
	from app.rb:8:in `<class:ConsulNetwork>'
	from app.rb:6:in `<main>'
```

Not sure if it's just me (I've no experience with sinatra apps but seems pretty easy to use framework) or just that on your local configuration you have something that makes it work locally.

Thank you so much for this project ❤️  👏

**Comment by ortegacmanuel** [comment]
In order to run it locally, after the bundle, just type `rackup` on the project's directory

Happy to read your comment! Thanks to you for all the help and shared knowledge.

I added the local dev steps to the README 👍 Thanks!

**Comment by bertocq** [comment]
Awesome @ortegacmanuel thanks for the readme update 🙏 😃 , working! 👏 

I would add `open http://localhost:9292 to check the project on your browser` 👌

**Comment by ortegacmanuel** [comment]
Added!
