### ISSUE TITLE
More Consul installations

### ISSUE THREAD

**Issue by bertocq** [ortegacmanuel/consulnetwork#2]
First thank you so much for this project and time invested :). We loved it at ConsulCon today and we'll think with your help about how to make something across consul installations work truly further than just showing info from them. 👏 😍 😊 

Although consul has graphql api available ... not all forks have updated their codebase so it can be used, and the scraping seems like best option right now to do this :)

Here some more consul installs we know about that have proposals!
- https://participa.benalmadena.es/proposals
- https://baelige.buenosaires.gob.ar/proposals
- http://vote.kolhaam.org.il/proposals?locale=en (content is in Hebrew)
- http://participa.ciudaddemendoza.gob.ar/proposals
- https://decide.molinadesegura.es/proposals
- https://www.participacalvia.es/proposals
- https://decide.aytochiloeches.es/proposals
- https://decide.carreno.es/proposals
- https://cheste.participago.dival.es/proposals

I was going to create a PR, but since you'll need to grab the logo images and ... I was going to suggest the usage of a json/yml file and grabbing the logos from the websites directly (hotlinking) but not sure you'll like that part 😅

**Comment by ortegacmanuel** [comment]
@bertocq  It's a big pleasure! Great! already willing to start helping and talking with you on how to make something across consult installations. I love federation and Consul :D 

I like the idea about the json/yml file. Just added this as a issue :) 

About the logos directly from the website I don't really know how to make it in the best way. My first idea was to take the images during the scrapping from each proposal but almost none proposal on the websites have an image so them I decided to use a logo for them. 

I'll start adding all those new consul installations now 👍
